name: Z Old SnapEnhance Patch core.apk and Release

on:
  workflow_dispatch:

env:
  APK_NAME: patched-snapchat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(echo ${{ steps.setup-java.outputs.java-home }})" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for github-action-get-previous-tag

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
        shell: bash

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Install pup
        run: |
         wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip -O pup.zip
         unzip pup.zip
         chmod +x pup
         sudo mv pup /usr/local/bin/
        working-directory: . 

      - name: Grant execute permissions to script
        run: chmod +x betascript.sh
        working-directory: .  

      - name: Run APK Download Script
        run: |
         ./betascript.sh  

      - name: Run the command
        run: |
          java -jar lspatch.jar -m "$GITHUB_WORKSPACE/core.apk" -f -l 2 -v snap.apk

      - name: Rename apk
        run: |
          mv ./snap-402-lspatched.apk ./${{ env.APK_NAME }}.apk
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APK_NAME }}.apk
          path: ./${{ env.APK_NAME }}.apk

      - name: Get previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: 1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: REGEX the release tag
        id: REGEX_tag
        uses: frabert/replace-string-action@v2
        with:
          pattern: '(\d+)\.(\d+)\.(\d+)'
          string: ${{ steps.previoustag.outputs.tag }}
          replace-with: '$3'

      - name: Get next minor version
        id: semver
        uses: 'WyriHaximus/github-action-next-release-version@v1'
        with:
          version: ${{ steps.REGEX_tag.outputs.replaced }}

      - name: Create and Publish Release
        id: create_release_id
        uses: softprops/action-gh-release@v2.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.patch }}
          name: Release ${{ steps.semver.outputs.patch }}
          files: |
            ${{ env.APK_NAME }}.apk
          

