name: Test the Snapchat Download Script

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # required for github-action-get-previous-tag

    - name: Grant execute permissions to script
      run: chmod +x script.sh
      working-directory: .

    - name: Run APK Download Script
      run: |
        ./script.sh

    - name: Show Files
      run: ls -la
